### ISSUE TITLE
Final link failure while executing setup script on Heroku

### ISSUE THREAD

**Issue by harrydrippin** [jlaine/aiortc#39] opened 2018-07-14 23:32 UTC
Hello,

I experienced some weird error on `examples/server` project while I pushing these codes to Heroku instance for testing purpose. I can execute this on my local environment but Heroku instance can't.

Error was occurred when `setup.py` was ran. I tried to debug this with several methods such as changing Heroku stack or adding some `apt-get`s during build, but I couldn't figure out what's happening. 

I did `apt-get build-essential gcc libopus-dev libvpx-dev` on instance first, and instance uses Python 3.6.

Error summary is below:
`relocation R_X86_64_PC32 against symbol 'vpx_rv' can not be used when making a shared object; recompile with -fPIC`

And setup history and failure logs are below:
```
Running setup.py install for aiortc: started
Running setup.py install for aiortc: finished with status 'error'
Complete output from command /app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qbrycl28/aiortc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8b9pktnw-record/install-record.txt --single-version-externally-managed --compile:
        running install
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-3.6
        creating build/lib.linux-x86_64-3.6/aiortc
        copying aiortc/sdp.py -> build/lib.linux-x86_64-3.6/aiortc
        ... copying some .py files ...
        copying aiortc/codecs/opus.py -> build/lib.linux-x86_64-3.6/aiortc/codecs
        running build_ext
        generating cffi module 'build/temp.linux-x86_64-3.6/aiortc.codecs._vpx.c'
        creating build/temp.linux-x86_64-3.6
        generating cffi module 'build/temp.linux-x86_64-3.6/aiortc.codecs._opus.c'
        building 'aiortc.codecs._opus' extension
        ... successfully built the opus extension ...
        building 'aiortc.codecs._vpx' extension
        gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/app/.heroku/python/include/python3.6m -c build/temp.linux-x86_64-3.6/aiortc.codecs._vpx.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/aiortc.codecs._vpx.o
        gcc -pthread -shared build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/aiortc.codecs._vpx.o -lvpx -o build/lib.linux-x86_64-3.6/aiortc/codecs/_vpx.abi3.so
        /usr/bin/x86_64-linux-gnu-ld: /tmp/build_fec03df77a0d0bb84c5472a5fe135ee7/.apt/usr/lib/x86_64-linux-gnu/libvpx.a(deblock_sse2.asm.o): relocation R_X86_64_PC32 against symbol `vpx_rv' can not be used when making a shared object; recompile with -fPIC
        /usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
        collect2: error: ld returned 1 exit status
        error: command 'gcc' failed with exit status 1
```

**Comment by jlaine** [comment] 2018-07-16 14:07
I found a couple of reports of similar issues:

https://groups.google.com/a/webmproject.org/forum/#!topic/webm-discuss/trEJtgeAvCg
https://bugs.chromium.org/p/webm/issues/detail?id=46

The suggested fix seems to be adding `-fvisibility=protected` to the cflags.

Could you try adding adding the following to src/build_vpx.py:

`    extra_compile_args=['-fvisibility=protected'],`

.. just before:

`    libraries=['vpx'])`

**Comment by harrydrippin** [comment] 2018-07-16 18:47
I did exactly you suggested but there was no effect with `gcc` parameter, so I changed `extra_compile_args` to `extra_link_args` to fix this problem and tried again but also failed.

I also tried `-fvisibility=hidden` and some other compiler or linker options like `-fPIC` or some `-fdisable` things to `ffibuilder.set_source()` but failed.

```python
ffibuilder.set_source('aiortc.codecs._vpx', """
#include <vpx/vpx_decoder.h>
...
    """,
    extra_link_args=['-fvisibility=protected'],
    libraries=['vpx'])
```

**Comment by jlaine** [comment] 2018-07-16 22:41
That's odd, when I make the changes the flags definitely appear in the gcc invocation.

Can I ask what version of Ubuntu heroku is providing you with? Our continuous integration (on travis) is running on Ubuntu 14.04 (for Python 3.5 and 3.6) and Ubuntu 16.04 (for Python 3.7) without any issues. I'm also not experiencing any linker errors on Debian/unstable.

**Comment by harrydrippin** [comment] 2018-07-16 23:02
I currently using [Heroku-16](https://devcenter.heroku.com/articles/heroku-16-stack) which was built on Ubuntu 16.04. I changed to `extra_compile_args` from `extra_link_args` again but still error occurs. It's also very weird to me, so I'll check this error on Heroku's Docker image and Ubuntu 16.04 Docker image, and talk to you later if I have more questions. 

Thanks for your support!

**Comment by harrydrippin** [comment] 2018-07-23 17:05
I don't know why the build failure is occurred on Heroku still, but I succeed to build on my own Docker instance. I tested this on Heroku and my container both with exactly same configurations but It runs successfully on my own Docker container but fails on Heroku. Here is my tested Dockerfile:

```
FROM ubuntu:16.04

ADD ./ ~/server
WORKDIR ~/server

RUN apt-get update
RUN apt-get install -y build-essential libssl-dev libffi-dev libopus-dev libvpx-dev libgtk2.0-dev
RUN apt-get install -y python3-dev python3-pip python3-pkg-resources python3-setuptools libpython-all-dev
RUN pip3 install aiohttp aiortc opencv-python

EXPOSE 8080

CMD ["python3", "server.py"]
```

**Comment by jlaine** [comment] 2018-07-23 19:35
That's so weird, are the docket images supposed to reflect herokus exactly?

**Comment by harrydrippin** [comment] 2018-07-24 17:23
I can show you the configuration files above Heroku which I configured.

First, this is `Aptfile`, which Heroku reads and executes `apt-get` to all listed individuals.
```
build-essential
libssl-dev
libffi-dev
libopus-dev
libvpx-dev
libgtk2.0-dev
python3-dev 
python3-pip
python3-pkg-resources
python3-setuptools 
ibpython-all-dev
```

And this is `requirements.txt`, which executes after `apt-get`s above.
```
aiohttp
opencv-python
aiortc
```

**Comment by jlaine** [comment] 2018-07-25 08:15
I have been able to reproduce the issue with heroku, and I'm starting to think there's something wrong with the "apt" buildpack.

- The libvpx version being installed is the same for heroku and for travis: `1.5.0-2ubuntu1`.

- Heroku however seems to install its .deb packages in a non-standard location: instead of going to /usr they are installed to /tmp/xxx/.apt/usr

My hypothesis is that due to this, the shared library version of libvpx is not being picked up, and gcc instead tries to link against the static library. To test this hypothesis I deleted the following symlink on my local machine to force compilation against the static library:

```
rm /usr/lib/x86_64-linux-gnu/libvpx.so
```

.. and sure enough now my build fails:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libvpx.a(deblock_sse2.asm.o): relocation R_X86_64_PC32 against symbol `vpx_rv' can not be used when making a shared object; recompile with -fPIC```

**Comment by harrydrippin** [comment] 2018-07-26 19:20
I tested your hypothesis too, and found the same result on my machine. So I think that now we have a conclusion for this issue: this problem is absolutely not our fault, and have no idea to fix this without changing [buildpack source here](https://github.com/heroku/heroku-buildpack-apt/blob/master/bin/compile). It seems we have no method to change the installation directory except editing the source directly. Do you have any idea for fix this?

**Comment by jlaine** [comment] 2018-08-21 21:56
Sorry, I don't really know how to move this forward, it sounds like the build environment set up by the apt buildpack is broken.

**Comment by jlaine** [comment] 2018-09-26 13:34
I'm going to close this, I think this needs to be fixed in the buildpack. A likely cause is https://github.com/heroku/heroku-buildpack-apt/issues/35

**Closed by jlaine** 2018-09-26 13:34 UTC
Labels: invalid, wontfix
