### ISSUE TITLE
DTLS: Handshake fails when offering

### ISSUE THREAD

**Issue by lgrahl** [jlaine/aiortc#4] opened 2018-03-10 12:32 UTC
This is what OpenSSL *spits out* in RAWRTC:

```
tls: 140610245187392:error:14102410:SSL routines:dtls1_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_d1.c:772:SSL alert number 40
```

I can provide a pcap trace if needed.

**Comment by jlaine** [comment] 2018-03-10 14:48
Yes I would appreciate a pcap trace and possibly a program to reproduce. I have a feeling it has something to do with aiortc assuming the wrong client/server role

**Comment by jlaine** [comment] 2018-03-22 15:36
@lgrahl could you try to reproduce this in a fresh virtualenv? Now that cryptography 2.2 has been released, you should be able to use a prebuilt wheel, which should eliminate some noise from old OpenSSL versions.

**Comment by jlaine** [comment] 2018-05-18 10:14
@lgrahl I'm closing this issue as I really cannot reproduce it. Feel free to re-open if you can reproduce it in the conditions mentioned above.

**Closed by jlaine** 2018-05-18 10:14 UTC

**Comment by lgrahl** [comment] 2018-05-18 11:12
@jlaine Sorry for the delay. I currently need to work on my thesis but I'll come back to this and will try again. :slightly_smiling_face:

**Comment by jlaine** [comment] 2018-12-30 09:53
This may be related to #115
