### ISSUE TITLE
Full support to ice connection state

### ISSUE THREAD

**Issue by dsvictor94** [jlaine/aiortc#25] opened 2018-06-07 08:32 UTC
I Try to detect when connection failed but its appear that iceConnectionState only support a subset of states described at spec (https://w3c.github.io/webrtc-pc/#dom-rtciceconnectionstate)

reading the code I believe this is the current implementation status:

- [x] new
- [x] checking
- [ ] connected
- [x] completed
- [ ] disconnected
- [x] failed
- [x] closed

**Comment by dsvictor94** [comment] 2018-06-07 21:29
To detect disconnection I did the follow
```python
    pc = RTCPeerConnection(RTCConfiguration(bundlePolicy=bundlePolicy))
    sender = pc.addTrack(CameraVideoTrack(camera, framerate=(camera.framerate-1)))

    @sender.transport.on('statechange')
    async def change_state():
        logger.debug('change sender state to %s', sender.transport.state)
        if sender.transport.state == 'closed':
            logger.debug('closing %s becouse remote disconnection', session)
            await pc.close()
``` 

but the `await pc.close()` fails trying to send the shutdown
```
Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe... connected',)>) at /home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe... connected',)>) at /home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/3.5.3/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/home/victor/.pyenv/versions/3.5.3/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/victor/fxdata/pfcount/pfcount/app.py", line 58, in change_state
    await pc.close()
  File "/home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/aiortc/rtcpeerconnection.py", line 179, in close
    await self.__sctp.stop()
  File "/home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/aiortc/rtcsctptransport.py", line 540, in stop
    await self._shutdown()
  File "/home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/aiortc/rtcsctptransport.py", line 895, in _shutdown
    await self._send_shutdown_maybe()
  File "/home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/aiortc/rtcsctptransport.py", line 866, in _send_shutdown_maybe
    await self._send_chunk(chunk)
  File "/home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/aiortc/rtcsctptransport.py", line 832, in _send_chunk
    await self.transport.data.send(bytes(packet))
  File "/home/victor/.pyenv/versions/3.5.3/envs/pfcount/lib/python3.5/site-packages/aiortc/rtcdtlstransport.py", line 422, in _send_data
    raise ConnectionError('Cannot send encrypted data, not connected')
ConnectionError: Cannot send encrypted data, not connected
```

This is a bug or a expected result? in case it is a expected result, how can I release the resources associated with this RTCPeerConnection?

Thank you

**Comment by jlaine** [comment] 2018-06-18 19:53
Hm. It's certainly not a very satisfactory outcome.

I'm starting to wonder if we should really be doing a clean SCTP shutdown, the browser implementations seem happy to just abort.. @lgrahl what are your thoughts?

**Comment by lgrahl** [comment] 2018-06-18 19:55
Yep, we've settled on mandatory to implement sending an `ABORT` chunk in the WebRTC 1.0 spec now.

**Comment by jlaine** [comment] 2018-06-18 19:57
Ah that's good to know. And what's the expected behavior if you *receive* a shutdown request? Should you just ignore it?

The reason I'm asking is that if I can just prune all the code related to shutdown it's going to shrink the codebase quite a bit!

**Comment by lgrahl** [comment] 2018-06-18 20:10
There's nothing explicitly specified but it certainly shouldn't trigger any kind of panicking. IIRC you can answer with an `ABORT` in case you receive a `SHUTDOWN`, so that should simplify it a bit.

**Comment by jlaine** [comment] 2018-06-18 22:51
Thanks for the tips @lgrahl, I've updated the SCTP code to send an ABORT chunk which leads to a simpler shutdown sequence.

@dsvictor94 I have reworked the code so that an error sending ABORT doesn't bomb. Could you check you no longer get an error please?

**Comment by jlaine** [comment] 2018-10-15 14:54
@dsvictor94 I have added support for the "failed" ICE connection state.

**Comment by jlaine** [comment] 2018-10-18 07:12
I'm going to close this issue, as I don't have any means of handling "transient" states like "disconnected".

**Closed by jlaine** 2018-10-18 07:12 UTC
