### ISSUE TITLE
Allow aiortc to be used as a pure Python module

### ISSUE THREAD

**Issue by sametmax** [jlaine/aiortc#118] opened 2019-01-11 16:18 UTC
Currently, installing aiortc fail if you don't have the libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config modules installed on linux.

However, correct me if I'm wrong, but they are only useful if you wish to use sound or or video. For pure data, they are not required, are they ?

If that's the case, I would suggest to allow the package to be able to be installed in 3 modes:

```bash
pip install aiortc # pure Python, for data only
pip install aiortc[audio] # with audio support
pip install aiortc[video] # with audio and video support
```

This can be done with the "extras" section in setup.py.

Indeed, webrtc is useful already without audio or video, it solves a complex problems with TURN and STUN servers, encryption and a way for 2 peers to connect to each others. And it does not in a standard way, that works out of the box in the web browser.

Hence, any program wanting to exchange data peer 2 peer may want to implement just the data part of webrtc, which can be done without complex media dependencies and be deployed in a bigger set of plateforms (anywhere where the dependency wheels exist).

**Comment by jlaine** [comment] 2019-01-11 17:07
This is a duplicate of #78

**Closed by jlaine** 2019-01-11 17:07 UTC
