### ISSUE TITLE
Cannot use requested address on server example

### ISSUE THREAD

**Issue by eufat** [jlaine/aiortc#52] opened 2018-08-09 07:24 UTC
Using server example in https://github.com/jlaine/aiortc/tree/master/examples/server, then changing its port to another port, not 8080 (ex. 2000, since I cannot use the default 8080 port in WSL since it used to another service) throwing this error while running the video example.

![issue](https://user-images.githubusercontent.com/3710666/43884173-9a4c3bb4-9bdf-11e8-898d-e1b6db559243.PNG)

Environment:
Ubuntu 16.04 WSL
Windows 10 Build 17134
Python 3.5.2

**Comment by eufat** [comment] 2018-08-09 07:28
Also in here is SDP offer logs (media, data channel and answer is empty) in demo.

v=0
o=- 5597590717937569160 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video data
a=msid-semantic: WMS yX0MnPLKs7FW3dAhzwzjo9nSeQd6NBHcpKWq
m=audio 49514 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 192.168.100.150
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:1416285991 1 udp 2122260223 192.168.100.150 49514 typ host generation 0 network-id 1 network-cost 10
a=candidate:451490775 1 tcp 1518280447 192.168.100.150 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:fv3o
a=ice-pwd:wvLeVpzanS0vmVFl7hcH5DWN
a=ice-options:trickle
a=fingerprint:sha-256 C9:F9:DA:39:DB:1C:B5:7F:5E:F0:24:DB:AD:B6:85:BF:54:BB:0A:82:85:E3:A4:ED:65:EC:40:90:E6:EC:6C:1F
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1211459837 cname:m5er8osMXFMALz1j
a=ssrc:1211459837 msid:yX0MnPLKs7FW3dAhzwzjo9nSeQd6NBHcpKWq 1ad63d3f-540e-4602-ba59-640901a8f2e2
a=ssrc:1211459837 mslabel:yX0MnPLKs7FW3dAhzwzjo9nSeQd6NBHcpKWq
a=ssrc:1211459837 label:1ad63d3f-540e-4602-ba59-640901a8f2e2
m=video 49516 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 123 127 122 125 107 108 109 124
c=IN IP4 192.168.100.150
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:1416285991 1 udp 2122260223 192.168.100.150 49516 typ host generation 0 network-id 1 network-cost 10
a=candidate:451490775 1 tcp 1518280447 192.168.100.150 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:fv3o
a=ice-pwd:wvLeVpzanS0vmVFl7hcH5DWN
a=ice-options:trickle
a=fingerprint:sha-256 C9:F9:DA:39:DB:1C:B5:7F:5E:F0:24:DB:AD:B6:85:BF:54:BB:0A:82:85:E3:A4:ED:65:EC:40:90:E6:EC:6C:1F
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 red/90000
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 ulpfec/90000
a=ssrc-group:FID 519448567 2964504695
a=ssrc:519448567 cname:m5er8osMXFMALz1j
a=ssrc:519448567 msid:yX0MnPLKs7FW3dAhzwzjo9nSeQd6NBHcpKWq 90e90746-45d7-4f6e-ac07-112172565da1
a=ssrc:519448567 mslabel:yX0MnPLKs7FW3dAhzwzjo9nSeQd6NBHcpKWq
a=ssrc:519448567 label:90e90746-45d7-4f6e-ac07-112172565da1
a=ssrc:2964504695 cname:m5er8osMXFMALz1j
a=ssrc:2964504695 msid:yX0MnPLKs7FW3dAhzwzjo9nSeQd6NBHcpKWq 90e90746-45d7-4f6e-ac07-112172565da1
a=ssrc:2964504695 mslabel:yX0MnPLKs7FW3dAhzwzjo9nSeQd6NBHcpKWq
a=ssrc:2964504695 label:90e90746-45d7-4f6e-ac07-112172565da1
m=application 49515 DTLS/SCTP 5000
c=IN IP4 192.168.100.150
a=candidate:1416285991 1 udp 2122260223 192.168.100.150 49515 typ host generation 0 network-id 1 network-cost 10
a=candidate:451490775 1 tcp 1518280447 192.168.100.150 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:fv3o
a=ice-pwd:wvLeVpzanS0vmVFl7hcH5DWN
a=ice-options:trickle
a=fingerprint:sha-256 C9:F9:DA:39:DB:1C:B5:7F:5E:F0:24:DB:AD:B6:85:BF:54:BB:0A:82:85:E3:A4:ED:65:EC:40:90:E6:EC:6C:1F
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024

**Comment by jlaine** [comment] 2018-08-10 20:35
There is a `--port` command line argument so you can run:

`python3 server.py --port 2000`

.. or whatever port is appropriate for your local config.

PS: one issue = one specific problem so I have removed the unrelated comment, feel free to open another issue for it.

**Comment by eufat** [comment] 2018-08-11 01:28
@jlaine thankyou for the answer, but it still won't work though
![capture2](https://user-images.githubusercontent.com/3710666/43986754-74bad2fe-9d40-11e8-8f06-d05209351252.PNG)
![capture](https://user-images.githubusercontent.com/3710666/43986755-74f1441a-9d40-11e8-9dbe-79821fdd10d4.PNG)

**Comment by jlaine** [comment] 2018-08-11 02:29
WSL seems to have a specific issue whereby certain network addresses cannot be used:

https://github.com/jlaine/aioice/issues/6

The issue is fixed in the latest aioice code, I need to tag an aioice release and push it out.

**Comment by jlaine** [comment] 2018-08-12 15:59
aioice 0.6.5 is tagged and will reach pypi shortly, solving this issue.

**Closed by jlaine** 2018-08-12 15:59 UTC

**Comment by eufat** [comment] 2018-08-13 04:49
Thankyou @jlaine, confirmed working as intended with aioice 0.6.5
